branches:
  only:
    - master

sudo: required

language: 

#before_script:
#  - apt-get update -yqq 
#  - apt-get install -yqq bash

script:
  - sudo bash deploy/deploy.sh
#  - bash test/test.sh

services:
  - apache

#after_success:
#  - sh .travis/deploy_dockerhub.sh
#- test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
