branches:
  only:
    - master

sudo: required

language:

#before_script:
#  - apt-get -yqq install bash

script:
  - sudo bash deploy/deploy.sh
#  - bash test/test.sh

services:
  - docker

after_success:
  - sh deploy/travis_deploy_dockerhub.sh
#- test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
