branches:
  only:
    - master

sudo: required

language:

before_script:
  - apt-get -yqq update
  - apt-get -yqq upgrade
#  - apt-get -yqq install bash
  - apt-get -yqq clean
  - apt-get -yqq autoremove
script:
  - sudo bash deploy/deploy.sh
#  - bash test/test.sh

services:
  - docker

after_success:
  - sh .travis/deploy_dockerhub.sh
#- test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
